import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

import Footer from "./components/general/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  test,
}: Readonly<{
  children: React.ReactNode;
  test: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <div className="flex flex-grow px-4 pt-8">{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
